### ISSUE TITLE
obfuscation

### ISSUE THREAD

**Issue by Sch8ill** [Mehran1022mm/ServerStatus#1]
why is your code obfuscated?
I deobfuscated it and ther is nothing you have to hide, you just use mcstatus to query the data and colorama to make some colourfull output.
There is really no reason to obfuscate this stuff.
Windows defender blocks your code emmidiatly, because the obfuscation technic your are using is used by many viruses. lol

**Comment by Mehran1022mm** [comment]
Hi. Ok i will deobfuscated and commit the new one
Thanks for the issue. ❤️
